GET http://localhost:4000/posts
Accept: application/json

###
GET http://localhost:4000/posts/2
Accept: application/json

###
GET http://localhost:4000/characters
Accept: application/json

###
GET http://localhost:4000/characters?id=1011334
Accept: application/json

###
GET http://localhost:4000/bio?id=1011334
Accept: application/json
